services:
  - type: web
    name: cnn-detection-api
    runtime: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "mysql://avnadmin:YOUR_DATABASE_PASSWORD@mysql-2f60f75f-nguyentrivinhntv-6ab4.f.aivencloud.com:12210/defaultdb?ssl-mode=REQUIRED"
      - key: GOOGLE_CLIENT_ID
        value: "467356155966-9tv52397cuqllc6pe02c9fc32j1nfb8j.apps.googleusercontent.com"
